### ISSUE TITLE
incorrect markup on "like" permalinks

### ISSUE THREAD

**Issue by aaronpk** [blackaf/koype#2]
I've found a few problems with the markup on "like" permalinks. This is easiest to see once you're looking at the parsed result rather than looking at the markup.

* PERMALINK: https://v2.jacky.wtf/post/0e3be1ff-5dec-49ff-94d1-21b3348a17d3
* PARSED: https://pin13.net/mf2/?url=https%3A%2F%2Fv2.jacky.wtf%2Fpost%2F0e3be1ff-5dec-49ff-94d1-21b3348a17d3

### empty `<section>` 

There are two `<section>` tags that have no content, but include `e-name e-content` classes, which means the parsed result ends up having these in the parsed result:

```json
"name": [
  {
    "html": "",
    "value": "",
    "lang": "en"
  }
],
"content": [
  {
    "html": "",
    "value": "",
    "lang": "en"
  }
],
```

These tags appear both in the `h-cite` as well as in the `h-entry`.

**Either the section tag or the classes should be removed to avoid this empty value in the parsed result.**

### Missing author name

The author `h-card` of the cited tweet is missing a name. I see that you've included the Twitter user's name in the `title` attribute of the `<img>`, but if you move that to the `alt` attribute then it'll parse correctly. e.g.:

```html
<a href="https://twitter.com/JadaFBabyy_" class="h-card u-author ma1 h2 link color-inherit v-mid">
--
  | <img title="princess 🍯" alt="princess 🍯" class="u-photo h-100 center v-mid" src="https://pbs.twimg.com/profile_images/1125938096917364736/UsBAyHXg_normal.jpg" />
  | </a>
```

**Comment by jalcine** [comment]
Thanks for reporting this!

I’ve patched this up in https://github.com/blackaf/koype/commit/4c119209b63854043c8a101d8dfad21f5905d78d with some tests.

(Originally published at: https://v2.jacky.wtf/post/9ace9f8b-1df5-4643-9cae-5613301c17a0)
