### ISSUE TITLE
Incorrect mf2 markup on stream pages

### ISSUE THREAD

**Issue by aaronpk** [blackaf/koype#3]
I'm looking at https://v2.jacky.wtf/stream and there are a few issues with the mf2 markup.

### Wrong author of the `h-entry`s

* ORIGINAL: https://v2.jacky.wtf/stream
* PARSED: https://pin13.net/mf2/?url=https://v2.jacky.wtf/stream

For likes and reposts, the `author` property of the `h-entry`s appears to be the author of the post being liked/reposted. This ends up looking wrong in readers, since you're supposed to be the author of your likes/reposts.

**Comment by jalcine** [comment]
Also closed this with the changes made in https://github.com/blackaf/koype/commit/4c119209b63854043c8a101d8dfad21f5905d78d

(Originally published at: https://v2.jacky.wtf/post/0fd63da1-d674-42fe-a91d-0b30ea987ccd)
